name: Dispatcher
on:
  push:
    branches: [main]

jobs:
  dispatch:
    name: Dispatch
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['dragonhunt02/v-sekai-game']
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflow 
        run: |
            curl -v -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            --data '{"event_type": "some_event", "client_payload": { "commit_sha": "bar" }}' \
            https://api.github.com/repos/${{ matrix.repo }}/dispatches

            gh api \
             --method POST \
             -H "Accept: application/vnd.github+json" \
             /repos/${{ matrix.repo }}/dispatches \
              -f "event_type=on-demand-test" -F "client_payload[unit]=false" -F "client_payload[integration]=true"
