name: Dispatcher
on:
  push:
    branches: [main]

permissions:
  contents: write
  repository-projects: write

jobs:
  dispatch:
    name: Dispatch
    env:
      GITHUB_TOKEN1: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN2: ${{ secrets.DISPATCH }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['dragonhunt02/v-sekai-game']
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflow 
        run: |
            curl -v -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN1}" \
            --data '{"event_type": "some_event", "client_payload": { "commit_sha": "bar" }}' \
            https://api.github.com/repos/${{ matrix.repo }}/dispatches

            echo "Start github gh..."

            #URL=' \
            gh api \
             --method POST \
             -H "Accept: application/vnd.github+json" \
             /repos/${{ matrix.repo }}/dispatches \
              -f "event_type=on-demand-test" -F "client_payload[unit]=false" \
              -F "client_payload[integration]=true" 
            # '
